name: mainproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  google_maps_flutter: ^2.14.0
  location: ^5.0.1
  provider: ^6.1.5+1
  razorpay_flutter: ^1.4.0
  confetti: ^0.8.0
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.11
  google_fonts: ^8.0.0
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.3.0
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

 

    
